Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -48,20 +48,6 @@ commands:
         default: "High"
     steps:
       - run:
-          # run zap baseline against the server
-          # Only fail on error code 1, which indicates at least one FAIL was found.
-          # error codes 2 & 3 indicate WARN or other, and should not break the run
-          name: Run OWASP ZAP Baseline
-          
-          command: |
-            docker pull owasp/zap2docker-weekly
-            (
-              
-              docker run -t owasp/zap2docker-weekly zap-baseline.py \
-                  -t https://google-gruyere.appspot.com/409976138208656853771250675759008232039/ ;
-              if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
-            )
-      - run:
           command: |
             set -e
             cd arachni-1.5.1-0.5.12
@@ -126,6 +112,20 @@ jobs:
         default: "High"
     steps:
       - setup_arachni
+      - run:
+          # run zap baseline against the server
+          # Only fail on error code 1, which indicates at least one FAIL was found.
+          # error codes 2 & 3 indicate WARN or other, and should not break the run
+          name: Run OWASP ZAP Baseline
+          
+          command: |
+            docker pull owasp/zap2docker-weekly
+            (
+              
+              docker run -t owasp/zap2docker-weekly zap-baseline.py \
+                  -t https://google-gruyere.appspot.com/409976138208656853771250675759008232039/ ;
+              if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+            )
       - run:
           command: |
             cd arachni-1.5.1-0.5.12
